### ISSUE TITLE
open, save, save image,  gives invalid folder name error.

### ISSUE THREAD

**Issue by EricGebhart** [sboesebeck/ErgodoxLayoutGenerator#10]
I cannot open, save, or create image of a layout.   I have set the qmk source dir to the qmk source tree.

I thought it might be my window manager causing problems,  I use Xmonad.  But I tried it with FVWM and had the same behavior.  I am running on a recently updated Arch which is only  a few months old to start with.  

I did have to compile ELG to get it to work.  

If there is a dialog, I never see it.  I click and get the error.

I suspect they all give the same error. Some errors are handled and some are not.
open shows a traceback to the terminal I run it from.

```
Caused by: java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:238)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:190)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1496)
	at javafx.stage.FileChooser.showDialog(FileChooser.java:416)
	at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:350)
	at de.caluga.ergodox.Main.openKeymap(Main.java:1149)
	... 57 more
```

The save image error is handled.

```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at de.caluga.ergodox.Main.saveAsPng(Main.java:1003)
	at de.caluga.ergodox.Main.lambda$start$17(Main.java:499)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at  
```

Save does this, which is again, I believe the same problem.

```
java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:238)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:190)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1496)
```

**Comment by EricGebhart** [comment]
I have been able to succesfully load a keymap.  I am not quite sure, but I have reproduced the behavior once so far.  If I go to set qmk source dir and cancel,  Then doing an open will give a file dialog and allow me to select a file.   Otherwise no dialog is displayed and I get a traceback.

I still cannot save, or save image.  At one point one of the errors I recieved was that qmk-sourcedir  was not set.  But it was actually displaying as set to the root of qmk-firmware.  I've tried setting it to various paths from the root of qmk-firmware down to my specific keymap.  I don't see any difference in behavior between them.

**Comment by EricGebhart** [comment]
The same trick does not work with save image.   Save image gives the error 
"**Cannot save image if QMK-Sourcedir is not set!"**

**Comment by ericlimer** [comment]
Having this same issue.
